export const movies = [
  { name : "The Shawshank Redemption"},
  { name : "The Dark Knight"},
  { name : "City of God"},
  { name : "Pulp Fiction"},
  { name : "Amélie"},
  { name : "12 Angry Men"},
  { name : "Blade Runner"},
  { name : "A Clockwork Orange"},
  { name : "The Deer Hunter"},
  { name : "Casablanca"},
  { name : "E.T. the Extra-Terrestrial"},
  { name : "Up"},
  { name : "The Rocky Horror Picture Show"},
  { name : "The Big Lebowski"},
  { name : "Office Space"},
  { name : "Fight Club"},
  { name : "Snatch"},
  { name : "Oldboy"},
  { name : "Leon: The Professional"},
  { name : "Scarface"},
  { name : "Raiders of the Lost Ark"},
  { name : "The Lord of the Rings Trilogy"},
  { name : "Moonlight"},
  { name : "The Matrix"},
  { name : "Apocalypse Now"},
  { name : "The Grand Budapest Hotel"},
  { name : "Life of Brian"},
  { name : "In Bruges"},
  { name : "3 Idiots"},
  { name : "The Godfather"},
  { name : "The Notebook"},
  { name : "The Lion King"},
  { name : "Stand by Me"},
  { name : "Dirty Dancing"},
  { name : "Jurassic Park"},
  { name : "2001: A Space Odyssey"},
  { name : "The Goonies"},
  { name : "WALL·E"},
  { name : "Groundhog Day"},
  { name : "Star Wars Episode IV, V, VI"},
  { name : "Schindler's List"},
  { name : "Breakfast at Tiffany's"},
  { name : "Shaun of the Dead"},
  { name : "Back to the Future"},
  { name : "Forrest Gump"},
  { name : "The Silence of the Lambs"},
  { name : "The Shining"},
  { name : "Alien"},
  { name : "Memento"},
  { name : "Se7en"},
  { name : "Halloween"},
  { name : "Jaws"},
  { name : "The Evil Dead"},
  { name : "Airplane!"},
  { name : "Mean Girls"},
  { name : "Lawrence of Arabia"},
  { name : "Drive"},
  { name : "Casino Royale"},
  { name : "Ghostbusters"},
  { name : "Rosemary's Baby"},
  { name : "Mary and Max"},
  { name : "The Terminator"},
  { name : "The Green Mile"},
  { name : "Rocky"},
  { name : "This Is Spinal Tap"},
  { name : "American Psycho"},
  { name : "Citizen Kane"},
  { name : "The Intouchables"},
  { name : "American History X"},
  { name : "Seven Samurai"},
  { name : "Gladiator"},
  { name : "The Good, the Bad and the Ugly"},
  { name : "Brokeback Mountain"},
  { name : "The Great Dictator"},
  { name : "Toy Story"},
  { name : "The Prestige"},
  { name : "Titanic"},
  { name : "Her"},
  { name : "Boyz N the Hood"},
  { name : "Four Weddings and a Funeral"},
  { name : "Little Miss Sunshine"},
  { name : "Trainspotting"},
  { name : "The Departed"},
  { name : "Saving Private Ryan"},
  { name : "No Country for Old Men"},
  { name : "The Pianist"},
  { name : "Dr. Strangelove"},
  { name : "Lagaan: Once Upon a Time in India"},
  { name : "Baahubali: The Beginning"},
  { name : "Psycho"},
  { name : "Vertigo"},
  { name : "The Truman Show"},
  { name : "Reservoir Dogs"},
  { name : "Amadeus"},
  { name : "Enter the Dragon"},
  { name : "The Wizard of Oz"},
  { name : "Gangs of New York"},
  { name : "The Usual Suspects"},
  { name : "Spirited Away"},
  { name : "Good Will Hunting"}
];